### ISSUE TITLE
babelify@6

### ISSUE THREAD

**Issue by mattdesl** [zertosh/errorify#4]
The error is no longer so pretty with babelify@6

https://github.com/babel/babelify/issues/72

I can submit a PR that looks something like this:

``` js
  var message;
  if (err.codeFrame) { //babelify@6.x
    message = [err.message, err.codeFrame].join('\n\n');
  } else { //babelify@5.x and browserify
    message = err.annotated || err.message;
  }

  //normalize error properties
  err = {
    message: message,
    ...
```

**Comment by zertosh** [comment]
Oh that's gross, but yeah, please submit a fix.

**Comment by zertosh** [comment]
^ please mention me so I get a notification :smile:

**Comment by zertosh** [comment]
@mattdesl I added you as a collaborator on github and npm: https://gist.github.com/substack/e205f5389890a1425233

**Comment by mattdesl** [comment]
Cool thanks :+1: Gonna tidy up the readme too

**Comment by mattdesl** [comment]
Pushed to npm. 

A minor irk is that the new `err.message` is just a long single line. :disappointed: 

babelify@6
![screen shot 2015-04-10 at 10 43 34 am](https://cloud.githubusercontent.com/assets/1383811/7090092/89f130e8-df6e-11e4-9b97-efaa7b06203e.png)

babelify@5
![screen shot 2015-04-10 at 10 44 53 am](https://cloud.githubusercontent.com/assets/1383811/7090111/a841537a-df6e-11e4-9b58-c795614087d1.png)

**Comment by zertosh** [comment]
@mattdesl Awesome! thanks!
